config/routes.rb
Rails.application.routes.draw do
  # resources :matches
  resources :matches do
	resources :games
  end
  resources :games
  resources :players
  resources :teams
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :match
  has_many :game_scores, :dependent => :destroy
  has_many :teams, :through => :game_scores
  belongs_to :winning_team, :class_name => 'Team', optional: true
  accepts_nested_attributes_for :game_scores
  before_create :create_game_scores
  before_save :set_winning_team
  validate :validate_scores
  after_save :set_match_winning_team, if: :winning_team_id?

  def create_game_scores
  	self.match.match_teams.each do |match_team|
		self.game_scores.build(:team_id => match_team.team_id, :score => 0)
	end
  end

  def validate_scores
  	max_score_team_ids = max_score_team
  	if max_score_team_ids.count > 1
  		errors.add(:base, 'Both teams should not have the maximum score')
  	end
  end

  def set_winning_team
  	self.winning_team_id = max_score_team.try(:first).try(:team_id)
  end

  def max_score_team
  	self.game_scores.select { |g_score| g_score.team_id if g_score.score == 5 }
  end

  def set_match_winning_team
	self.match.save(:winning_team_id => self.winning_team_id)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update]
  def index
  	@games = Games.all
  end

  def edit
  end

  def show
  end

  def update
  	respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game.match, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:winning_team_id, :game_scores_attributes => [:id,:score, :team_id])
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <table>

        <%# game.game_scores.each_with_index do |game_score_attributes, index| %>
          <%= form.fields_for :game_scores do |game_score_form|%>
            <tr>
              <th style="text-align: left;"> <%#= game_score.team.try(:name) %></th>
              <td> <%= game_score_form.select :team_id, team_array, :include_blank => true %></td>
              <td> <%= game_score_form.number_field :score, :min => 0, :max => 5 %></td>
            </tr>
          <% end %>
        <%# end %>
        <tr>
          <%= form.hidden_field :winning_team_id %>
          <%= hidden_field_tag 'selected', 'none'  %>
        </tr>
    <tr>
      <th style="text-align: left;"> </th>
      <td> <%= form.submit %></td>
    </tr>
  </table>
<% end %>

app/views/games/edit.html.erb
<h1>Game scores</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', match_path %>

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>