config/routes.rb
Rails.application.routes.draw do
  # resources :matches
  resources :matches do
	resources :games
  end
  resources :games
  resources :players
  resources :teams
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/match.rb
class Match < ApplicationRecord
	has_many :match_teams, :dependent => :destroy
	has_many :teams, :through => :match_teams
	belongs_to :winning_team, :class_name => 'Team', optional: true
	has_many :games, :dependent => :destroy
	has_many :game_scores, :through => :games
	accepts_nested_attributes_for :match_teams
	accepts_nested_attributes_for :games
	before_create :create_init_game
  	before_save :set_winning_team
  	after_save :update_game_teams
  	validate :validate_teams
 
  	def match_name
		team_names = self.teams.map { |t| t.name }
		team_names.join(' VS ')
	end

	def create_init_game
    	(1 .. 3).each {self.games.build}
  	end

  	def set_winning_team
  		self.winning_team_id = max_game_winner.try(:keys).try(:first)
  	end

  	def max_game_winner
  		team_wins = self.games.group(:winning_team_id).count
	  	winner = team_wins.select { |team, wins| team if wins > 1 }
	  	winner
	end	

	def validate_teams
		team_ids =  self.match_teams.map {|match_team| match_team.team_id}
		if team_ids.first == team_ids.last
			errors.add(:base, 'Match teams should not be the same')
		end
	end

	def update_game_teams
		team_ids =  self.match_teams.map {|match_team| match_team.team_id}
		self.game_scores.order(:game_id).each_with_index do |game_score,index|
			game_score.team_id = team_ids[index%2]
			game_score.save
		end
	end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  include PlayersHelper
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.includes(:winning_team).all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @games = @match.games
  end

  # GET /matches/new
  def new
    @match = Match.new
    #@match.match_teams.build(2) # = [MatchTeam.new(@match), MatchTeam.new(@match)]
    2.times { @match.match_teams.build }
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)
    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:winning_team_id, :match_teams_attributes => [:id, :team_id])
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <table>
         <% is_first_team = true %>
         <%= form.fields_for :match_teams do |match_teams_form|%>
            <tr style="text-align: center;">

              <td style="text-align: center;"> <%= match_teams_form.select :team_id, team_array, :include_blank => true %></td>
            </tr>
            <% if is_first_team %>
             <th style="text-align: center;"> <%= "VS" %></th>
             <% is_first_team = false %>
            <% end %>
          <% end %>
        <tr>
          <%= form.hidden_field :winning_team_id %>
          <%= hidden_field_tag 'selected', 'none'  %>
        </tr>
        <tr></tr>
        <tr>
          <td> <%= form.submit %></td>
        </tr>
        <tr></tr>
  </table>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>
<style type="text/css">
  #players {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#players td, #players th {
  border: 1px solid #ddd;
  padding: 8px;
}

#players tr:nth-child(even){background-color: #f2f2f2;}

#players tr:hover {background-color: #ddd;}

#players th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
}
</style>
<h1><%= t(:label_matches) %></h1>
<p style="float: right;"><%= link_to 'New Match', new_match_path %></p>
<table id="players">
  <thead>
    <tr>
      <th><%= t(:label_teams) %></th>
      <th>Winning team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.match_name %></td>
        <td><%= match.winning_team.try(:name) %></td>
        <td><%= link_to 'Game Details', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @match.match_name %></strong>
</p>
<p>
  <strong>Winning team:</strong>
  <%= @match.winning_team.try(:name) %>
</p>

<table class = 'tbl-report', border="1" style="border-collapse:collapse;" cellspacing="0",frame="box">
	<head style="text-align: center;"><b><%= t(:label_games) %></b></head>
  <% @games.each_with_index do |game, index| %>
    <tr>
     <th style="text-align: center;"><%= "Game#{index+1}" %></th>
     <td><%= link_to 'Start', edit_match_game_path(@match,game) %></td>
    </tr>
    <% game.game_scores.each do |game_score| %>
	    <tr>
	      <th style="text-align: left;"><%= game_score.team.try(:name) %></th>
	      <td> <%= game_score.score %></td>
	    </tr>
	<% end %>
	<tr>
      <th style="text-align: left;"><%= "Winning team:" %></th>
      <td> <%= game.winning_team.try(:name) %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>