config/routes.rb
Rails.application.routes.draw do
  # resources :matches
  resources :matches do
	resources :games
  end
  resources :games
  resources :players
  resources :teams
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/views/layouts/admin.html.erb
<%= render :file => "layouts/base" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FantasyFoosball</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<%= stylesheet_link_tag 'jquery/jquery-ui-1.11.0', 'application', 'responsive', :media => 'all' %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<title><%= html_title %></title>
 <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover:not(.active) {
  background-color: red;
}

.active {
  background-color: #4CAF50;
}
</style>



</head>
<body>
	<ul>
  		
  		<li><%= link_to t(:label_players),players_path %></li>
  		<li><%= link_to t(:label_teams),teams_path %></li>
  		<li><%= link_to t(:label_matches), matches_path %></li>
 		
	</ul>
    <div id="content">
        <% #= render_flash_messages %>
        <%= yield %>
        <% #= call_hook :view_layouts_base_content %>
        <div style="clear:both;"></div>
    </div>


</body>
</html>